Add support of versioning

diff --git a/.github/workflows/PushToGHCR.yml b/.github/workflows/PushToGHCR.yml
--- a/.github/workflows/PushToGHCR.yml
+++ b/.github/workflows/PushToGHCR.yml
@@ -40,6 +40,7 @@ jobs:
           tags: ghcr.io/${{ env.REPO_LOWERCASE }}/${{ env.BRANCH_LOWERCASE }}:v${{ secrets.RELEASE_MAJOR }}.${{ secrets.RELEASE_MINOR }}
 
   update_version:
+    needs: build_and_push
     runs-on: ubuntu-latest
     steps:
       - name: Checkout repository
@@ -78,19 +79,16 @@ jobs:
       - 
         name: Verify the version number is updated for the next build
         run: |
-          RELEASE_MINOR_SET=$(gh secret list -R ${{ github.repository }} | grep RELEASE_MINOR | awk '{print $2}')
-          RELEASE_MAJOR_SET=$(gh secret list -R ${{ github.repository }} | grep RELEASE_MAJOR | awk '{print $2}')
+          FINAL_RELEASE_MINOR=$(echo "${{ secrets.RELEASE_MINOR }}" | awk '{print $1}')
+          FINAL_RELEASE_MAJOR=$(echo "${{ secrets.RELEASE_MAJOR }}" | awk '{print $1}')
           
-          if [ "${RELEASE_MINOR_SET}" != "${{ env.NEW_RELEASE_MINOR }}" ]; then
-            echo "ERROR: Failed to bump the version. Please check the secret pane!" >&2
+          if [ "${FINAL_RELEASE_MINOR}" != "${{ env.NEW_RELEASE_MINOR }}" ]; then
+            echo "ERROR: Failed to bump the minor version. Please check the secret pane!" >&2
             exit 1
-          elif [ "${RELEASE_MAJOR_SET}" != "${{ env.NEW_RELEASE_MAJOR }}" ]; then
-            echo "Setting the RELEASE_MAJOR version failed" >&2
+          elif [ "${FINAL_RELEASE_MAJOR}" != "${{ env.NEW_RELEASE_MAJOR }}" ]; then
+            echo "ERROR: Failed to bump the major version. Please check the secret pane!" >&2
             exit 1
           else
             echo "Successfully bumped the version."
           fi
-        env:
-          GH_TOKEN: ${{ github.token }}
 
-  
